name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy-production:
    name: Deploy to Heroku Production
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Deploy to Heroku Production
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_PRODUCTION_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        procfile: "web: node server.js"
        healthcheck: "https://${{ secrets.HEROKU_PRODUCTION_APP_NAME }}.herokuapp.com/api/health"
        checkstring: "ok"
        delay: 5
        rollbackonhealthcheckfailed: true
